// Shipped-renderer identity presentation contracts; no acoustic claims.
const test=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
const {frontend}=require('./support/frontend_dom.cjs');
const root=process.env.FRONTEND_SOURCE_ROOT||path.resolve(__dirname,'..');
// Frozen synthetic Engine -> MeetingRefinement -> saved /api/jobs controls.
// Generated by the independent backend lane; no user recording or model run.
const jobs=require('./support/unknown_speaker_jobs.json');

function fixture(status,speakers,owners) {
  const f=frontend(root);f.seed(owners.length,status);
  f.context.names=speakers;f.context.owners=owners;
  f.run('doc.speakers=structuredClone(names);doc.segments.forEach((s,i)=>s.speaker=owners[i]);window.original=JSON.stringify(doc);renderEditor()');
  return f;
}
const cards=f=>f.document.getElementById('segments').children;
const label=card=>card.querySelector('.name-speaker')?.textContent ||
  card.querySelector('select').children.find(option=>option.selected)?.textContent;

for(const status of ['ready','recording']) {
  test(`${status}: distinct unnamed stable tracks retain labels, IDs and same-owner continuation`,()=>{
    const f=fixture(status,{speaker_0:'Speaker 1',speaker_1:'Speaker 2'},['speaker_0','speaker_1','speaker_1','speaker_0']);
    assert.deepEqual(cards(f).map(c=>c.dataset.segmentId),['r0','r1','r2','r3']);
    assert.deepEqual(cards(f).map(c=>c.dataset.speaker),['speaker_0','speaker_1','speaker_1','speaker_0']);
    assert.deepEqual(cards(f).map(label),['Speaker 1','Speaker 2','Speaker 2','Speaker 1']);
    assert.deepEqual(cards(f).map(c=>c.classList.contains('speaker-continuation')),[false,false,true,false]);
    assert.equal(f.run('JSON.stringify(doc)===original'),true);
  });

  test(`${status}: generic unassigned words do not imply one unknown person`,()=>{
    const f=fixture(status,{unassigned:'Unknown speaker',speaker_0:'Speaker 1'},['unassigned','unassigned','speaker_0']);
    assert.deepEqual(cards(f).map(label),['Speaker unassigned','Speaker unassigned','Speaker 1']);
    assert.equal(cards(f)[1].classList.contains('speaker-continuation'),false,'Unassigned is an attribution state, not a shared speaker identity');
    assert.deepEqual(cards(f).slice(0,2).map(c=>c.querySelector('.speaker-avatar').textContent),['?','?']);
    const names=f.document.getElementById('speaker-list');
    assert.equal(names.querySelectorAll('button').length,1,'Only the stable track can be named or remembered');
    if(status==='recording')assert.equal(cards(f)[0].querySelector('button.name-speaker'),null);
    else assert.ok(cards(f)[0].querySelector('select').children.some(option=>option.value==='speaker_0'),'Manual passage assignment stays available');
    assert.equal(f.run('JSON.stringify(doc)===original'),true);
  });
}

test('reading view keeps stable unnamed owners separate from words without attribution',()=>{
  const f=fixture('ready',{multiple_speakers:'Multiple speakers',speaker_0:'Speaker 1',speaker_1:'Speaker 2'},['multiple_speakers']);
  f.run(`(()=>{const parts=[['First. ','speaker_0','single'],['Second. ','speaker_1','single'],['Uncertain.','unassigned','unknown']];let offset=0;
    const s=doc.segments[0];s.text=parts.map(p=>p[0]).join('');s.reading_turns=parts.map(([text,speaker,attribution])=>{
      const start_offset=offset;offset+=Array.from(text).length;return {text,speaker,attribution,start_offset,end_offset:offset,start:null,end:null};});
    window.original=JSON.stringify(doc);renderSegments();})()`);
  assert.deepEqual(cards(f)[0].querySelectorAll('.reading-turn-speaker').map(e=>e.textContent),['Speaker 1','Speaker 2','Speaker unassigned']);
  assert.equal(f.run('JSON.stringify(doc)===original'),true);
});

for(const status of ['ready','recording'])for(const name of Object.keys(jobs)) {
  test(`${status}: saved API control ${name} preserves ownership and scoped evidence`,()=>{
    const f=frontend(root);f.seed(1);f.context.apiJob=jobs[name];
    f.run(`selected=structuredClone(apiJob);selected.status='${status}';selected.refinement_status='complete';
      doc=structuredClone(selected.document);doc.segments.forEach(s=>s.refinement_state='refined');
      window.original=JSON.stringify(doc);renderEditor()`);
    const c=cards(f)[0],qualified=name.startsWith('qualified');
    assert.equal(cards(f).length,1,'One canonical passage remains one editable card');
    assert.equal(c.dataset.segmentId,'utterance-e7298777cff7dea9ac701b95');
    assert.equal(c.querySelector('textarea').value,'Alpha. Still alpha. Beta. Still beta.');
    if(qualified)assert.deepEqual(c.querySelectorAll('.reading-turn-speaker').map(e=>e.textContent),['Speaker 1','Speaker 2']);
    else {
      assert.equal(label(c),'Speaker unassigned');
      assert.equal(c.querySelectorAll('.reading-turn').length,0,'Activity alone never assigns words to either person');
    }
    if(name.endsWith('candidate')) {
      let evidenceHost=c;
      if(status==='ready'){c.querySelector('.passage-details-toggle').click();evidenceHost=f.document.getElementById('segment-details');}
      const receipt=JSON.parse(evidenceHost.querySelector('.passage-evidence pre').textContent).speaker_track_mapping;
      assert.deepEqual(receipt.raw_batch_turns.map(t=>t.speaker),['speaker_7','speaker_8']);
      assert.deepEqual(receipt.mapping,qualified?{speaker_7:'speaker_0',speaker_8:'speaker_1'}:{});
      assert.ok(!evidenceHost.querySelector('.passage-evidence').open,'Diagnostics remain collapsed');
    }
    assert.equal(f.run('JSON.stringify(doc)===original'),true);
  });
}

test('refinement changes a retained naming control without losing the typed correction or caret',()=>{
  const f=fixture('recording',{unassigned:'Unknown speaker',speaker_0:'Speaker 1'},['unassigned']);
  const c=cards(f)[0],text=c.querySelector('textarea');
  text.focus();text.value='Exact human correction';text.dispatchEvent({type:'input'});text.setSelectionRange(2,8);
  f.run("doc.segments[0].speaker='speaker_0';doc.segments[0].machine_revision=2;window.named=null;openNamePicker=async id=>named=id;nameSpeaker=id=>named=id;renderSegments()");
  assert.equal(cards(f)[0],c);assert.equal(c.querySelector('textarea'),text);assert.equal(f.document.activeElement,text);
  assert.equal(text.value,'Exact human correction');assert.equal(text.selectionStart,2);assert.equal(text.selectionEnd,8);
  assert.equal(label(c),'Speaker 1');c.querySelector('button.name-speaker').click();
  assert.equal(f.run('named'),'speaker_0','Naming uses the current attributed track');
  f.run("doc.segments[0].speaker='unassigned';doc.segments[0].machine_revision=3;renderSegments()");
  assert.equal(label(c),'Speaker unassigned');assert.equal(c.querySelector('button.name-speaker'),null);
  assert.equal(c.querySelector('.speaker-avatar').textContent,'?');assert.equal(text.value,'Exact human correction');
});
